# Generated by Django 3.1.5 on 2021-01-28 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='notdefined', max_length=20, verbose_name='文章分类')),
            ],
        ),
        migrations.CreateModel(
            name='Mypost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(default='此文章无标题', max_length=50, verbose_name='文章标题')),
                ('post_text', models.TextField(default='此文章无摘要', verbose_name='文章摘要')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='发布日期')),
                ('post_update_date', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('post_article', models.FileField(default='statics/posted/default/default_posted.md', upload_to='statics/posted/%Y/%m/', verbose_name='博客文件')),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
        ),
    ]
