# Generated by Django 3.1.5 on 2021-01-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_mypost_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='name',
            field=models.CharField(default='undefined', max_length=20, verbose_name='文章分类'),
        ),
    ]
